//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Gdb : DbContext
    {
        public Gdb()
            : base("name=Gdb")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Contest> Contests { get; set; }
        public virtual DbSet<Input_Cases> Input_Cases { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<Output_Cases> Output_Cases { get; set; }
        public virtual DbSet<Problem> Problems { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Submission> Submissions { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
