//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Submission
    {
        public int Problem_ID { get; set; }
        public int User_ID { get; set; }
        public string Text_Code { get; set; }
        public byte Status { get; set; }
        public int Memory { get; set; }
        public double Execution_Time { get; set; }
        public int Langage_ID { get; set; }
        public System.DateTime Submission_Time { get; set; }
    
        public virtual Problem Problem { get; set; }
        public virtual User User { get; set; }
    }
}
