//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GApi.Models
{
    using GApi.Services;
    using System;
    using System.Collections.Generic;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Contests = new HashSet<Contest>();
            this.Submissions = new HashSet<Submission>();
            this.Contests1 = new HashSet<Contest>();
        }

        public int id { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public int R_ID { get; set; }
        public string UserName { get; set; }
        public string Name { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contest> Contests { get; set; }
        public virtual Role Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Submission> Submissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contest> Contests1 { get; set; }

        public static explicit operator User(RegisterBinding item)
        {
            User user = new User();
            user.UserName = user.Name = item.Name;
            user.Email = item.Email;
            user.Password = item.Password;
            user.R_ID = 1;

            return user;
        }
    }
}
